Repository Step3-kakao-tech-campus/Team14_FE, pull requests merged in 2023-10, with the labels that each got.

#13 페이지별 게시물 조회 카드 Skeleton UI 구현
  src/components/CardInfoContainer.jsx
  src/components/HomeCardButtonContainer.jsx
  src/components/MyCardButtonContainer.jsx
  src/components/PopCardButtonContainer.jsx
  src/pages/Skeleton/HomeCardSkeleton.jsx
  src/pages/Skeleton/MyCardSkeleton.jsx
  src/pages/Skeleton/PopCardSkeleton.jsx
  src/pages/Skeleton/SkeletonCount.jsx
  src/pages/Skeleton/SkeletonHashTag.jsx
  src/pages/Skeleton/SkeletonIcon.jsx
  src/pages/Skeleton/SkeletonTitle.jsx
Labels: Type: Feature, Type: Design

#15 모달 컴포넌트 생성
  package-lock.json
  package.json
  src/App.js
  src/components/Modal.jsx
  src/pages/TestPage/TestPage.jsx
Labels: Type: Feature, Type: Design

#16 스켈레톤 UI 리팩토링 및 게시물 레이아웃 생성
  src/components/CardInfoContainer.jsx
  src/components/HomeCardButtonContainer.jsx
  src/components/MyCardButtonContainer.jsx
  src/components/PopCardButtonContainer.jsx
  src/components/Post.jsx
  src/components/PostInfos.jsx
  src/pages/Skeleton/HomeCardSkeleton.jsx
  src/pages/Skeleton/MyCardSkeleton.jsx
  src/pages/Skeleton/PopCardSkeleton.jsx
  src/pages/Skeleton/SkeletonCount.jsx
  src/pages/Skeleton/SkeletonHashTag.jsx
  src/pages/Skeleton/SkeletonIcon.jsx
  src/pages/Skeleton/SkeletonTitle.jsx
  src/pages/SkeletonPage/SkeletonPage.jsx
  src/pages/SkeletonPage/components/SkeletonIcon.jsx
  src/pages/SkeletonPage/components/SkeletonInfos.jsx
  src/pages/TestPage/TestPage.jsx
Labels: Type: Feature, Type: Refactor, Type: Design

#17 인기 게시물 상세 조회 페이지 생성 + 건형님 Modals 삭제
  package-lock.json
  package.json
  src/App.js
  src/components/Modals/ModalPortal.js
  src/components/Modals/ModalTemplate.jsx
  src/components/Modals/OneBtnModal.jsx
  src/components/Modals/TwoBtnModal.jsx
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Card.jsx
  src/pages/SkeletonPage/SkeletonPage.jsx
  src/pages/TestPage/TestPage.jsx
Labels: Type: Feature, Type: Refactor, Type: Design

#19 Swiper 설치
  package-lock.json
  package.json
Labels: Type: Chore

#21 더블 클릭시 중앙에 좋아요 애니메이션 생성
  src/components/Post.jsx
Labels: Type: Feature, Type: Design

#20 마이페이지 틀 제작
  package-lock.json
  public/icons/Info.png
  public/icons/Setting.png
  public/icons/Upload.png
  public/icons/accountIcon.png
  public/icons/like.png
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/AccountInfoTemplate.jsx
  src/pages/MyPage/components/Button.jsx
  src/pages/MyPage/components/Container.jsx
  src/pages/MyPage/components/KakaoAccount.jsx
  src/pages/MyPage/components/MyAlbumTemplate.jsx
  src/pages/MyPage/components/PhotoCard.jsx
  src/pages/MyPage/components/PhotoList.jsx
  src/pages/MyPage/components/Text.jsx
Labels: Type: Feature, Type: Design

#22 설정 페이지 UI 생성
  src/App.js
  src/assets/Expand_left.png
  src/assets/Expand_left.svg
  src/pages/SettingPage/SettingPage.jsx
  src/pages/SettingPage/components/ListItem.jsx
Labels: Type: Feature, Type: Design

#23 홈 페이지 Swiper 적용
  src/assets/Play_fill.png
  src/assets/Play_fill.svg
  src/assets/Stop_fill.png
  src/assets/Stop_fill.svg
  src/components/IconButton.jsx
  src/components/Modal.jsx
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
Labels: Type: Bug, Type: Feature, Type: Design

#25 업로드 페이지 생성
  public/index.html
  src/assets/Close_round_light.png
  src/assets/Close_round_light.svg
  src/components/ModalButton.jsx
  src/components/Post.jsx
  src/components/PostInfos.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/TestPage/TestPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Feature, Type: Design

#27 홈페이지 클릭/더블클릭 이벤트 구분
  src/pages/HomePage/HomePage.jsx
Labels: Type: Bug

#26 내 상세 게시물 페이지 생성, 설정 페이지 연결 및 framer-motion 적용
  src/App.js
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/AccountInfoTemplate.jsx
  src/pages/MyPage/components/Button.jsx
  src/pages/MyPage/components/KakaoAccount.jsx
  src/pages/MyPage/components/MyAlbumTemplate.jsx
  src/pages/MyPage/components/PhotoCard.jsx
  src/pages/MyPage/components/PhotoList.jsx
  src/pages/SettingPage/SettingPage.jsx
Labels: Type: Feature, Type: Design

#28 마이 페이지 리팩토링 및 업로드 버튼 생성
  src/App.js
  src/assets/Export.png
  src/assets/Export.svg
  src/assets/Favorite_fill.png
  src/assets/Favorite_fill.svg
  src/assets/Setting_line.png
  src/assets/Setting_line.svg
  src/assets/info_light.png
  src/assets/info_light.svg
  src/components/IconButton.jsx
  src/pages/TestPage/TestDetailPage.jsx
  src/pages/TestPage/TestPage.jsx
  src/pages/TestPage/components/Card.jsx
  src/pages/TestPage/components/InstaProfile.jsx
  src/pages/TestPage/components/KaKaoProfile.jsx
  src/pages/TestPage/components/MyInfos.jsx
  src/pages/TestPage/components/SettingButton.jsx
  src/pages/TestPage/components/Text.jsx
  src/pages/TestPage/components/UploadButton.jsx
Labels: Type: Feature, Type: Refactor, Type: Design

#29 마이페이지 리팩토링 코드로 반영
  src/App.js
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/AccountInfoTemplate.jsx
  src/pages/MyPage/components/Button.jsx
  src/pages/MyPage/components/Card.jsx
  src/pages/MyPage/components/Container.jsx
  src/pages/MyPage/components/InstaProfile.jsx
  src/pages/MyPage/components/KaKaoProfile.jsx
  src/pages/MyPage/components/KakaoAccount.jsx
  src/pages/MyPage/components/MyAlbumTemplate.jsx
  src/pages/MyPage/components/MyInfos.jsx
  src/pages/MyPage/components/PhotoCard.jsx
  src/pages/MyPage/components/PhotoList.jsx
  src/pages/MyPage/components/SettingButton.jsx
  src/pages/MyPage/components/Text.jsx
  src/pages/MyPage/components/UploadButton.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/TestPage/TestDetailPage.jsx
  src/pages/TestPage/TestPage.jsx
  src/pages/TestPage/components/Text.jsx
Labels: Type: Refactor

#30 사진 보관함 사진 선택 기능 구현
  src/App.js
  src/components/NavigationBar.jsx
  src/index.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/UploadButton.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/recoil/uploadImage/atom.js
Labels: Type: Feature, Type: Design

#32 업로드 완료 페이지 구현
  src/App.js
  src/components/ModalExtraButton.jsx
  src/pages/UploadPage/UploadDonePage.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/theme.js
Labels: Type: Feature, Type: Design

#35 마이 페이지 내 폭죽 모달 생성
  src/assets/Img_box.png
  src/assets/Img_box.svg
  src/assets/happy.png
  src/assets/happy.svg
  src/assets/happy_happy.png
  src/assets/happy_happy.svg
  src/assets/insta.png
  src/assets/insta.svg
  src/components/Modal.jsx
  src/pages/MyPage/components/InfoModal.jsx
  src/pages/MyPage/components/MyInfos.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Feature, Type: Design

#36 카카오 로그인 모달 생성, axios, tanstack/react-query 설치
  package-lock.json
  package.json
  src/ auth/kakao/auth.js
  src/App.js
  src/components/Loader.jsx
  src/components/NavigationBar.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Container.jsx
Labels: Type: Feature, Type: Design, Type: Chore

#37 폴더 이름 문제 해결
  src/auth/kakao/auth.js
  src/components/NavigationBar.jsx
Labels: Type: Bug

#38 업로드 페이지-건형 리팩토링
  src/App.js
  src/pages/UploadPage/ToUploadPage.jsx
Labels: Type: Refactor

#39 업로드완료 페이지 리팩토링
  src/App.js
  src/pages/UploadPage/UploadDonePage.jsx
Labels: Type: Refactor

#40 업로드 완료 페이지에 쓸 recoil state 생성
  src/components/ModalExtraButton.jsx
  src/components/NavigationBar.jsx
  src/pages/UploadPage/UploadDonePage.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/recoil/uploadContents/atom.js
  src/theme.js
Labels: Type: Feature, Type: Design

#42 카카오, 인스타그램 로직 담당 컴포넌트 생성
  src/App.js
  src/apis/index.js
  src/auth/instagram/auth.js
  src/auth/kakao/auth.js
  src/components/HeartLoader.jsx
  src/components/InstagramHandler.jsx
  src/components/KakaoHandler.jsx
  src/components/Loader.jsx
  src/components/NavigationBar.jsx
  src/components/Post.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/UploadButton.jsx
Labels: Type: Feature, Type: Design

#43 api 요청 코드 임시 생성
  src/apis/api/post.js
  src/apis/api/user.js
  src/apis/index.js
  src/components/KakaoHandler.jsx
  src/components/NavigationBar.jsx
  src/index.js
  src/pages/MyPage/MyPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Feature

#45 API 일부 연결
  src/apis/api/post.js
  src/apis/api/user.js
  src/apis/index.js
  src/components/InstagramHandler.jsx
  src/components/KakaoHandler.jsx
  src/components/Modal.jsx
  src/components/NavigationBar.jsx
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/Card.jsx
  src/pages/MyPage/components/InstaProfile.jsx
  src/pages/MyPage/components/KaKaoProfile.jsx
  src/pages/MyPage/components/MyInfos.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Card.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Feature
