Repository Step3-kakao-tech-campus/Team14_FE, pull requests merged in 2023-11, with the labels that each got.

#46 로그아웃, 회원탈퇴, 로그인(리프레시 토큰 로직 생성)
  src/apis/api/user.js
  src/apis/index.js
  src/pages/SettingPage/SettingPage.jsx
Labels: Type: Feature

#47 미로그인 주소 접근 차단, 마이페이지 좋아요
  src/App.js
  src/layouts/RequiredAuthLayout.jsx
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
Labels: Type: Feature

#48 인기 페이지 좋아요 낙관적 업데이트(미완성)
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
Labels: Type: Feature

#49 https 환경 설정 및 인스타그램 연결
  .gitignore
  package.json
  src/auth/instagram/auth.js
  src/auth/kakao/auth.js
  src/components/InstagramHandler.jsx
  src/components/Post.jsx
  src/pages/MyPage/MyPage.jsx
Labels: Type: Chore

#50 이미지 경로 수정
  src/apis/index.js
  src/components/Post.jsx
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/Card.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Card.jsx
Labels: Type: Refactor

#51 사용하지 않는 파일 삭제 및 유틸 함수 분리
  public/favicon.ico
  public/icons/Info.png
  public/icons/Setting.png
  public/icons/Upload.png
  public/icons/accountIcon.png
  public/icons/download.png
  public/icons/like.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/assets/Close_round_light.png
  src/assets/Close_round_light.svg
  src/assets/Expand_left.png
  src/assets/Expand_left.svg
  src/assets/Export.png
  src/assets/Export.svg
  src/assets/Favorite.png
  src/assets/Favorite.svg
  src/assets/Favorite_fill.png
  src/assets/Favorite_fill.svg
  src/assets/Home.png
  src/assets/Home.svg
  src/assets/Img_box.png
  src/assets/Img_box.svg
  src/assets/Import.png
  src/assets/Import.svg
  src/assets/Play_fill.png
  src/assets/Play_fill.svg
  src/assets/Search.png
  src/assets/Search.svg
  src/assets/Setting_line.png
  src/assets/Setting_line.svg
  src/assets/Stop_fill.png
  src/assets/Stop_fill.svg
  src/assets/User_alt.png
  src/assets/User_alt.svg
  src/assets/happy.png
  src/assets/happy.svg
  src/assets/happy_happy.png
  src/assets/happy_happy.svg
  src/assets/info_light.png
  src/assets/info_light.svg
  src/assets/insta.png
  src/assets/insta.svg
  src/components/ModalButton.jsx
  src/components/NavigationBar.jsx
  src/components/Post.jsx
  src/index.js
  src/layouts/RequiredAuthLayout.jsx
  src/pages/MyPage/components/InstaProfile.jsx
  src/pages/MyPage/components/KaKaoProfile.jsx
  src/pages/MyPage/components/SettingButton.jsx
  src/pages/MyPage/components/UploadButton.jsx
  src/pages/UploadPage/UploadPage.jsx
  src/pages/UploadPage/components/Button.jsx
  src/utils/convertToK.js
  src/utils/handleInstagramLogin.js
  src/utils/handleKaKaoLogin.js
Labels: Type: Refactor, Type: Chore

#52 마이페이지 정보 렌더링, 캐시타임 삭제, 에러처리 일부
  .gitignore
  package.json
  src/App.js
  src/layouts/AuthLayout.jsx
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/MyInfos.jsx
Labels: Type: Bug, Type: Refactor, Type: Chore

#53 폭죽 사용 모달 생성 및 로직 추가(미완성)
  src/apis/api/post.js
  src/components/IconButton.jsx
  src/components/Post.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
Labels: Type: Feature, Type: Design

#56 마이페이지 변수 백엔드 데이터와 매칭
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/MyInfos.jsx
Labels: Type: Chore

#55 폭죽 사용 로직 완료
  src/apis/api/post.js
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
Labels: Type: Bug, Type: Feature

#57 My 페이지 로더 추가 및 userInfos 리팩토링
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/MyInfos.jsx
Labels: Type: Feature, Type: Refactor

#58 Home 페이지 무한스크롤 구현
  src/apis/api/post.js
  src/pages/HomePage/HomePage.jsx
Labels: Type: Feature

#59 로그인/인스타 연결 버그 해결 및 홈 리팩토링
  src/apis/api/post.js
  src/components/InstagramHandler.jsx
  src/components/KakaoHandler.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/SettingPage/SettingPage.jsx
Labels: Type: Bug, Type: Refactor

#60 인스타연결 타임아웃 수정
  src/apis/index.js
  src/components/InstagramHandler.jsx
Labels: Type: Bug

#61 my 페이지 무한스크롤
  src/apis/api/post.js
  src/apis/index.js
  src/components/Modal.jsx
  src/components/Post.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MyDetailpage/MyDetailPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/InfoModal.jsx
  src/pages/MyPage/components/InstaProfile.jsx
  src/pages/MyPage/components/MyInfos.jsx
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/UploadPage/UploadDonePage.jsx
  src/utils/preventScroll.js
Labels: Type: Feature, Type: Refactor

#62 로그아웃/회원탈퇴 모달 생성, 접근성 증가, 로더 재사용성 증가
  src/components/HeartLoader.jsx
  src/components/IconButton.jsx
  src/components/InstagramHandler.jsx
  src/components/KakaoHandler.jsx
  src/components/Post.jsx
  src/index.js
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/components/Card.jsx
  src/pages/MyPage/components/InstaProfile.jsx
  src/pages/MyPage/components/KaKaoProfile.jsx
  src/pages/MyPage/components/MyInfos.jsx
  src/pages/MyPage/components/SettingButton.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Card.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Feature, Type: Refactor, Type: Design

#63 인기 페이지 ui 튕김 이슈 해결, 이미지 드래그 방지
  src/index.js
  src/pages/PopDetailPage/PopDetailPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Card.jsx
Labels: Type: Bug

#64 불필요 코드 삭제 및 폴더 정리
  src/App.js
  src/components/Button.jsx
  src/components/Post.jsx
  src/pages/InstagramHandlerPage/InstagramHandlerPage.jsx
  src/pages/KakaoHandlerPage/KakaoHandlerPage.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/PopPage/PopPage.jsx
  src/pages/PopPage/components/Container.jsx
  src/pages/UploadDonePage/UploadDonePage.jsx
  src/pages/UploadPage/ToUploadPage.jsx
  src/pages/UploadPage/UploadPage.jsx
Labels: Type: Refactor
